server:
  port: 8083
  
spring:
  application:
    name: ConfigurationService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mggmanik/config.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.23.239.227:8761/eureka/
      
    register-with-eureka: true

info:
  app:
    name: Configuartion Service
    description: Configuartion service is up and has no problem
    version: 1.0.0
