spring:
  application:
    name: Community-service
  data:
    mongodb:
      database: communityDb
      host: localhost
      password: root
      port: 27017
      username: rajashri
  mail:
    host: smtp.gmail.com
    password: sarasingh9090
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: isamseil9090@gmail.com
eureka:
 client:
   register-with-eureka: true
   serviceUrl:
    defaultZone: http://172.23.239.227:8761/eureka
info:
  app:
    description: Message service is up and has no problem
    name: Message Service
    version: 1.0.0