eureka:
    client:
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
info:
    app:
        description: User service is up and has no problem
        name: User Service
        version: 1.0.0
server:
    port: 8093
spring:
    application:
        name: User-Service
    data:
        mongodb:
            database: UserServiceDB
            host: localhost
            password: root12
            port: 27017
            username: root12
