eureka:
  client:
    serviceUrl:
      defaultZone: http://172.23.239.227:8761/eureka/
    register-with-eureka: true

info:
  app:
    name: User Service
    description: User service is up and has no problem
    version: 1.0.0

spring:
  application:
    name: User-Service
  profiles:
    active: Development
  cloud:
    config:
      uri: http://172.23.239.104:8083