eureka:
    client:
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
info:
    app:
        description: Message service is up and has no problem
        name: Message Service
        version: 1.0.0
server:
    port: 8070
spring:
    application:
        name: Message-Service
    data:
        mongodb:
            database: MessageServiceDB
            host: localhost
            password: root123
            port: 27017
            username: root
