spring:
  kafka:
    consumer:
        auto-offset-reset: earliest
  data:
   cassandra:
     schema-action: CREATE_IF_NOT_EXISTS
     contact-points: localhost
     keyspace-name: message_key_space
#      port: 9042
#topic:
# boot: message
#server:
#  port: 9041