eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://172.23.239.227:8761/eureka/
info:
  app:
    description: Message service is up and has no problem
    name: Message Service
    version: 1.0.0

spring:
  application:
    name: Message-Service
  profiles:
    active: Development
  cloud:
    config:
      uri: http://172.23.239.104:8083
